// Code generated by mockery v2.14.0. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// WriterSumer is an autogenerated mock type for the WriterSumer type
type WriterSumer struct {
	mock.Mock
}

// Sum provides a mock function with given fields: b
func (_m *WriterSumer) Sum(b []byte) []byte {
	ret := _m.Called(b)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// Write provides a mock function with given fields: p
func (_m *WriterSumer) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	var r0 int
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewWriterSumer interface {
	mock.TestingT
	Cleanup(func())
}

// NewWriterSumer creates a new instance of WriterSumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWriterSumer(t mockConstructorTestingTNewWriterSumer) *WriterSumer {
	mock := &WriterSumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
