---
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
    creationTimestamp: null
    labels:
        app.kubernetes.io/name: emitter-fn
    name: emitter-fn
    namespace: redis
spec:
    env:
        - name: REDIS_HOST
          value: my-release-redis-master.redis.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
                key: redis-password
                name: my-release-redis
    runtime: nodejs22
    source:
        inline:
            dependencies: |
              {
                "name": "emitter-fn",
                "version": "0.0.1",
                "dependencies": {
                  "redis": "^4.6.13"
                }
              }
            source: |
              const { createClient } = require('redis');
              const LIST = "demo"


              module.exports = {
                main: async function (event, _) {

                  const port = process.env["REDIS_PORT"];
                  const host = process.env["REDIS_HOST"];
                  const password = process.env["REDIS_PASSWORD"];

                  const client = createClient({
                    password,
                    socket: {
                        host,
                        port,
                    }
                  });

                  client.on('error', err => console.log('Redis Client Error', err));

                  await client.connect();

                  var msg=event.extensions.request.body.msg
                  console.log(msg); 
                  const res1 = await client.lPush(LIST, msg);
                  console.log(res1); 

                }
              }


