# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "actions"
      include: "scope"
    ignore:
      - dependency-name: "gaurav-nelson/github-action-markdown-link-check"

  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "area/dependency"
      - "kind/chore"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
      include: "scope"
