
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: keda-admission-webhooks
    name: keda-admission-webhooks
    app.kubernetes.io/name: keda-admission-webhooks    
    helm.sh/chart: keda-2.18.0
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.18.0
    app.kubernetes.io/instance: keda
  name: keda-admission-webhooks
  namespace: kyma-system
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    to:
    - ipBlock:
        cidr: 0.0.0.0/0
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels:
          gardener.cloud/purpose: kube-system
      podSelector:
        matchLabels:
          k8s-app: node-local-dns
  - ports:
    - port: 8053
      protocol: TCP
    - port: 8053
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels:
          gardener.cloud/purpose: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  ingress:
  - from: []
    ports:
    - port: 9443
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kyma-system
      podSelector:
        matchLabels:
          networking.kyma-project.io/metrics-scraping: allowed
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app: keda-admission-webhooks
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: keda-operator
    name: keda-operator
    app.kubernetes.io/name: keda-operator    
    helm.sh/chart: keda-2.18.0
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.18.0
    app.kubernetes.io/instance: keda
  name: keda-operator
  namespace: kyma-system
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    to:
    - ipBlock:
        cidr: 0.0.0.0/0
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels:
          gardener.cloud/purpose: kube-system
      podSelector:
        matchLabels:
          k8s-app: node-local-dns
  - ports:
    - port: 8053
      protocol: TCP
    - port: 8053
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels:
          gardener.cloud/purpose: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kyma-system
      podSelector:
        matchLabels:
          networking.kyma-project.io/metrics-scraping: allowed
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app: keda-operator
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: keda-operator-metrics-apiserver
    app.kubernetes.io/name: keda-operator-metrics-apiserver    
    helm.sh/chart: keda-2.18.0
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.18.0
    app.kubernetes.io/instance: keda
  name: keda-operator-metrics-apiserver
  namespace: kyma-system
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    to:
    - ipBlock:
        cidr: 0.0.0.0/0
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels:
          gardener.cloud/purpose: kube-system
      podSelector:
        matchLabels:
          k8s-app: node-local-dns
  - ports:
    - port: 8053
      protocol: TCP
    - port: 8053
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels:
          gardener.cloud/purpose: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kyma-system
      podSelector:
        matchLabels:
          networking.kyma-project.io/metrics-scraping: allowed
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app: keda-operator-metrics-apiserver
  policyTypes:
  - Ingress
  - Egress
