name: 'Create k3d cluster'
description: 'Action for creating k3d cluster'

runs:
  using: 'composite'
  steps:
    - name: create single cluster
      uses: AbsaOSS/k3d-action@4e8b3239042be1dc0aed6c5eb80c13b18200fc79 #v2.4.0
      with:
        cluster-name: "k3dCluster"
        args: >-
          --agents 1
          --image rancher/k3s:v1.30.0-k3s1
          --port 80:80@loadbalancer
          --port 443:443@loadbalancer
          --wait
