# permissions for end users to edit kedas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: kyma-keda-edit
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - kedas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - kedas/status
  verbs:
  - get
