apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: http-echo-keda
  namespace: demo-app
spec:
  hosts:
  - "http-echo-keda.<YOUR_DOMAIN>"
  gateway: kyma-system/kyma-gateway
  rules:
  - path: /*
    methods: [ "GET", "POST", "PUT", "DELETE" ]
    noAuth: true
  service:
    name: keda-add-ons-http-interceptor-proxy
    namespace: <HTTP-ADD-ON-NAMESPACE>
    port: 8080
