apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: http-echo-keda
  namespace: demo-app
spec:
  hosts:
  - "http-echo-keda.${TEST_DOMAIN}"
  gateway: kyma-system/kyma-gateway
  rules:
  - path: /*
    methods: [ "GET", "POST", "PUT", "DELETE" ]
    noAuth: true
  service:
    name: keda-add-ons-http-interceptor-proxy
    namespace: kyma-system # The KEDA HTTP Add-on is installed in the kyma-system namespace by default
    port: 8080
