apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  labels:
    app.kubernetes.io/name: http-proxy-fn
  name: http-proxy-fn
spec:
  runtime: nodejs18
  replicas: 1
  source:
    gitRepository:
      url: https://github.com/kyma-project/examples.git
      baseDir: /scale-to-zero-with-keda/src/http-proxy-fn
      reference: main
  env:
    - name: eventspecversion
      value: "1.0"
    - name: eventsource
      value: kyma
    - name: eventtype
      value: sap.kyma.custom.acme.payload.received.v1
---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: http-proxy-fn
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: incoming
  rules:
  - accessStrategies:
    - handler: allow
    methods:
    - GET
    path: /.*
  service:
    name: http-proxy-fn
    port: 80