apiVersion: v1
kind: Namespace
metadata:
  name: keda-demo
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: keda-demo
  labels:
    app: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - name: httpbin
          image: "kennethreitz/httpbin:latest"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 20m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: keda-demo
  labels:
    app: httpbin
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: busybox
  namespace: keda-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox
        name: busybox
        command:
         - "/bin/sh"
         - "-c"
         - "--"
        args:
          - "while true; do sleep $SLEEP; wget -q -O- $URL > /dev/null ; done"
        env:
          - name: URL
            value: httpbin.keda-demo.svc.cluster.local/get
          - name: SLEEP
            value: '0.1'
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: httpbin-cpu-scaler
  namespace: keda-demo
spec:
  scaleTargetRef:
    name: httpbin
  minReplicaCount:  1
  maxReplicaCount:  10    
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "30"