apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: keda-dynatrace
  name: keda-dynatrace
spec:
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/created-by: kyma-cli
    app.kubernetes.io/name: httpbin
  name: httpbin
  namespace: keda-dynatrace
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  selector:
    app: httpbin
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: httpbin-metrics
  annotations:
    metrics.dynatrace.com/scrape: "true"
    metrics.dynatrace.com/port: "15090"         
    metrics.dynatrace.com/path: "/stats/prometheus" 
  name: httpbin-metrics
  namespace: keda-dynatrace
spec:
  ports:
  - port: 15090
    targetPort: 15090
    protocol: TCP
    name: http-istio-metrics
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/created-by: kyma-cli
    app.kubernetes.io/name: httpbin
  name: httpbin
  namespace: keda-dynatrace
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: httpbin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpbin
        sidecar.istio.io/inject: "true"
      name: httpbin
    spec:
      containers:
      - image: kennethreitz/httpbin
        imagePullPolicy: Always
        name: httpbin
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  labels:
    app.kubernetes.io/created-by: kyma-cli
    app.kubernetes.io/name: httpbin
  name: httpbin
  namespace: keda-dynatrace
spec:
  gateway: kyma-system/kyma-gateway
  hosts:
  - httpbin
  rules:
  - methods:
    - GET
    noAuth: true
    path: /*
  service:
    name: httpbin
    namespace: keda-dynatrace
    port: 80

