name: markdown
run-name: ${{github.event.pull_request.title}}

on:
  workflow_dispatch:
  push:
    branches: ["main", "release-*"]
jobs:
  documentation-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".mlc.config.json"
          folder-path: "."
          max-depth: -1
