name: pull
on:
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  contents: read # This is required for actions/checkout

jobs:
  unit-tests:
    uses: kyma-project/keda-manager/.github/workflows/_unit-tests.yaml@main

  experiment:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: |
        echo $FOO
      env:
        FOO: ${{ secrets.BTP_BACKEND_URL }}

  gitleaks:
    uses: kyma-project/keda-manager/.github/workflows/_gitleaks.yaml@main

  check-fips-image-versions:
    uses: kyma-project/keda-manager/.github/workflows/_check-fips-image-versions.yaml@main
    with:
      ref: ${{ github.event.pull_request.head.sha }}

