name: pull-build
on:
  pull_request_target:
    branches:
      - main
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  contents: read # This is required for actions/checkout

jobs:
  select-environment:
    runs-on: ubuntu-latest
    environment: restricted
    # uncomment after gating is allowed - environment: ${{ github.event.pull_request.author_association != 'COLLABORATOR' && github.event.pull_request.author_association != 'OWNER' && 'restricted' || 'internal' }}
    steps:
      - name: Approved
        run: echo "Build approved, environment selected"

  builds:
    needs: select-environment
    permissions:
      id-token: write # This is required for requesting the JWT token
      contents: read
    uses: ./.github/workflows/_build.yaml

  integrations:
    needs: builds
    uses: ./.github/workflows/_integration-tests.yaml
    with:
      image: europe-docker.pkg.dev/kyma-project/dev/keda-manager:PR-${{ github.event.number }}
