name: pull
on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  contents: read # This is required for actions/checkout

jobs:
  unit-tests:
    uses: ./.github/workflows/_unit-tests.yaml

  gitleaks:
    uses: ./.github/workflows/_gitleaks.yaml

  check-fips-image-versions:
    uses: ./.github/workflows/_check-fips-image-versions.yaml
    with:
      ref: ${{ github.event.pull_request.head.sha }}

