name: pull
on:
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize, reopened, ready_for_review]
  pull_request_target:
    branches:
      - release-1.11
permissions:
  contents: read # This is required for actions/checkout
jobs:
  unit-tests:
    uses: kyma-project/keda-manager/.github/workflows/_unit-tests.yaml@release-1.11
  gitleaks:
    uses: kyma-project/keda-manager/.github/workflows/_gitleaks.yaml@release-1.11
  check-fips-image-versions:
    uses: kyma-project/keda-manager/.github/workflows/_check-fips-image-versions.yaml@release-1.11
    with:
      ref: ${{ github.event.pull_request.head.sha }}
